### ISSUE TITLE
[B] - Fetch board from board items. (K)

### ISSUE THREAD

**Issue by serikkk** [Correlate-AS/communicate#6]
Search result board items on click lead to board page.
To generate search result link(action on click) board items should be able to fetch board itself.

**Comment by serikkk** [comment]
Added mechanism for board items to fetch parent item and board.

This mechanism should be updated, because:
Board can contain items. But items also can contain sub-items, and this can be recursive.
Current implementation does not support recursion.

**Comment by Anne-Emmanuelle** [comment]
@serikkk @norbertkeri how can we fix this and how long it could take (3 points estimation)?

**Comment by serikkk** [comment]
This was already done, turns out all items have attachment to board even if they are deeply nested.
Issue will be reopened if any problem with this occur.
